using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*
 *      Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *      By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */

namespace Even_Fibonacci_numbers
{
    class Program
    {
        static void Main(string[] args)
        {
            int current = 2;
            int pervious = 1;
            int summ = 0;
            while (current < 4E+6)
            {
                if (current % 2 == 0)
                    summ += current;

                int tmp = current;

                current += pervious;
                pervious = tmp;
            }
            Console.WriteLine(summ);
        }
    }
}
